const CONFIG=window.SPIDERGPT_CONFIG||{};const API=localStorage.getItem("spidergpt_api")||CONFIG.API_URL||"http://localhost:8000/api/v1";const SUPABASE_CLIENT=(window.supabase&&CONFIG.SUPABASE_URL&&CONFIG.SUPABASE_ANON_KEY)?window.supabase.createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_ANON_KEY):null;const KEY="spidergpt_access_token";const REFRESH="spidergpt_refresh_token";let state={user:null,spider:null,usage:null,messages:[],mode:"Brain"};
const plans={FREE:{name:"Free",price:"Free",responses:"30/day",modes:3},PRO:{name:"Pro",price:"₹399/mo",responses:"150/day",modes:5},PLUS:{name:"Plus",price:"₹999/mo",responses:"Unlimited",modes:6}};
async function api(path,opt={}){let h=new Headers(opt.headers||{});h.set("Content-Type","application/json");let t=localStorage.getItem(KEY);if(t)h.set("Authorization","Bearer "+t);let r=await fetch(API+path,{...opt,headers:h});let d=await r.json().catch(()=>({}));if(r.status===401){localStorage.removeItem(KEY)}if(!r.ok)throw Error(d?.error?.message||d?.detail||"Request failed");return d}
function go(path){location.hash=path}function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function shell(title,sub,body){return '<div class="shell"><aside class="sidebar" id="side"><div class="brand" onclick="go('/home')"><span class="brand-icon">🕷</span><div><b>SpiderGPT</b><small>Your AI Sidekick.</small></div></div><div class="nav">'+[['/home','⌂ Home'],['/chat','◉ Chat'],['/history','◷ History'],['/spider','🕷 My Spider'],['/saved','♡ Saved'],['/themes','◈ Themes'],['/settings','⚙ Settings']].map(x=>'<button onclick="go(\''+x[0]+'\')">'+x[1]+'</button>').join("")+'</div><button class="upgrade" onclick="go(\'/pricing\')">♛ Upgrade</button></aside><div class="mobile-nav" id="backdrop" style="display:none" onclick="closeMenu()"></div><main class="main"><header class="top"><button class="menu" onclick="openMenu()">☰</button><div><h1>'+title+'</h1><p>'+esc(sub||"")+'</p></div><button class="avatar" onclick="go(\'/profile\')">◯</button></header><div class="content">'+body+'</div></main></div>}
function openMenu(){document.querySelector("#side").classList.add("open");document.querySelector("#backdrop").style.display="block"}function closeMenu(){document.querySelector("#side").classList.remove("open");document.querySelector("#backdrop").style.display="none"}
function pageSplash(){return '<div class="splash"><div class="glow"></div><div><div class="spider">🕷</div><h1>SpiderGPT</h1><p class="muted">Your AI Sidekick.</p></div></div>'}
function pageWelcome(){return '<div class="auth"><div class="card"><div class="spider">🕷</div><h1>Meet your AI sidekick.</h1><p class="muted">Think. Create. Research. Roast. Your Spider is ready.</p><button class="primary wide" onclick="googleLogin()">Continue with Google</button><p class="muted" style="font-size:12px;margin-top:15px">Google OAuth is verified by the connected Supabase Auth backend.</p></div></div>'}
async function googleLogin(){if(!SUPABASE_CLIENT){alert("Configure frontend/config.js with your Supabase URL and anonymous key.");return}const r=await SUPABASE_CLIENT.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin+location.pathname}});if(r.error)alert(r.error.message)}
async function syncSession(){if(!SUPABASE_CLIENT||localStorage.getItem(KEY))return;const r=await SUPABASE_CLIENT.auth.getSession();const token=r.data.session?.access_token;if(!token)return;try{const x=await api("/auth/google",{method:"POST",body:JSON.stringify({access_token:token})});localStorage.setItem(KEY,x.access_token);if(x.refresh_token)localStorage.setItem(REFRESH,x.refresh_token);go(x.onboarding_completed?"/home":"/profile-setup")}catch(e){console.error(e)}}
function pageProfileSetup(){return '<div class="onboard"><div class="card"><span class="eyebrow">01 / 02</span><h1>Let’s get to know you.</h1><p class="muted">Your profile personalizes SpiderGPT.</p><label>Name<input id="pname" class="input" placeholder="What should we call you?"></label><label>Age<input id="page" class="input" type="number" min="13" placeholder="18"></label><button class="primary wide" onclick="saveProfile()">Continue →</button></div></div>'}
async function saveProfile(){try{await api("/profile/me",{method:"PUT",body:JSON.stringify({display_name:document.querySelector("#pname").value,age:Number(document.querySelector("#page").value)})});go("/create-spider")}catch(e){alert(e.message)}}
function pageCreateSpider(){let modes=["Brain","Chill","Chaos","Roast","Create","Focus"];return '<div class="onboard"><div class="card"><span class="eyebrow">02 / 02</span><h1>Create your Spider.</h1><p class="muted">Give your sidekick a name and starting personality.</p><input id="sname" class="input" value="Nova"><div class="mode-grid">'+modes.map(m=>'<button class="mode" onclick="this.parentNode.querySelectorAll('.mode').forEach(x=>x.style.borderColor='');this.style.borderColor='#ff3b30'" data-mode="'+m+'"><b>'+m+'</b></button>').join("")+'</div><button class="primary wide" onclick="createSpider()">Bring Spider to life →</button></div></div>'}
async function createSpider(){let b=document.querySelector(".mode[style*='border-color']")?.dataset.mode||"Brain";try{await api("/spider",{method:"POST",body:JSON.stringify({name:document.querySelector("#sname").value,personality_mode:b,appearance_id:"default"})});go("/home")}catch(e){alert(e.message)}}
async function load(){try{let [u,s]=await Promise.all([api("/usage"),api("/spider/me")]);state.usage=u;state.spider=s}catch(e){}}
async function pageHome(){await load();let plan=plans[state.usage?.plan_code]||plans.FREE;return shell("Good to see you"+(state.spider?.name?", "+esc(state.spider.name):"")+" .","Your sidekick is ready.",'<section class="hero"><div><span class="eyebrow">YOUR AI SIDEKICK</span><h2>What are we doing today?</h2><p class="muted">Ask, create, research, or just talk.</p><button class="primary" onclick="go(\'/chat\')">Start chatting →</button></div><div class="hero-spider">🕷</div></section><div class="grid"><button class="tile" onclick="go(\'/chat\')"><b>Chat with Spider</b><span>Get instant answers.</span></button><button class="tile" onclick="go(\'/personality\')"><b>Choose a mode</b><span>Switch Spider’s personality.</span></button><button class="tile" onclick="go(\'/pricing\')"><b>'+plan.name+' plan</b><span>'+plan.responses+' AI responses · '+plan.modes+'/6 modes</span></button></div><div class="quick"><button onclick="go(\'/chat\')">✦ Create</button><button onclick="go(\'/chat\')">⌕ Research</button><button onclick="go(\'/spider/customize\')">◈ Customize Spider</button></div>')}
function pageChat(){let modes=["Brain","Chill","Chaos","Roast","Create","Focus"];return shell("Chat","Talk to your Spider.",'<div class="mode-row">'+modes.map(m=>'<button class="'+(state.mode===m?"active":"")+'" onclick="state.mode=\''+m+'\';render()">'+m+'</button>').join("")+'</div><div class="messages">'+(state.messages.length?state.messages.map(m=>'<div class="bubble '+m.role+'">'+esc(m.content)+'</div>').join(""):'<div style="margin:auto;text-align:center" class="muted"><div class="spider">🕷</div><h2 style="color:#fff">What’s on your mind?</h2><p>I’m listening.</p></div>')+'</div><form class="composer" onsubmit="sendChat(event)"><input id="chatInput" placeholder="Message SpiderGPT…"><button class="send">→</button></form>')}
async function sendChat(e){e.preventDefault();let el=document.querySelector("#chatInput"),q=el.value.trim();if(!q)return;el.value="";state.messages.push({role:"user",content:q});render();try{let r=await api("/chat",{method:"POST",body:JSON.stringify({message:q,mode:state.mode})});state.messages.push({role:"assistant",content:r?.assistant_message?.content||r?.message||"Done."})}catch(x){state.messages.push({role:"assistant",content:x.message})}render()}
function generic(title,sub,content=""){return shell(title,sub,'<div class="card">'+(content||'<h2>'+title+'</h2><p class="muted">Connected to the SpiderGPT backend. This screen is ready for its account data and actions.</p>')+'</div>')}
function pagePersonality(){return generic("Personality","Choose how Spider talks to you.",'<div class="mode-grid">'+["Brain","Chill","Chaos","Roast","Create","Focus"].map(m=>'<button class="mode"><b>'+m+'</b><span>Spider’s '+m.toLowerCase()+' personality.</span></button>').join("")+'</div>')}
function pagePricing(){return shell("Plans","Choose how your Spider grows with you.",'<div class="plans">'+Object.keys(plans).map(p=>'<div class="plan '+(p==="PRO"?"featured":"")+'"><span class="eyebrow">'+p+'</span><h2>'+plans[p].name+'</h2><div class="price">'+plans[p].price+'</div><p class="muted">'+plans[p].responses+' AI responses</p><p class="muted">'+plans[p].modes+'/6 modes</p><button class="'+(p==="FREE"?"secondary":"primary")+' wide" onclick="'+(p==="FREE"?"go(\'/home\')":"go(\'/checkout/"+p+"\')")+'">'+(p==="FREE"?"Current plan":"Choose "+plans[p].name)+'</button></div>').join("")+'</div>')}
function pageCheckout(plan){let p=plans[plan]||plans.PRO;return generic("Checkout","Secure subscription checkout.",'<span class="eyebrow">SUBSCRIPTION</span><h2>'+p.name+' plan</h2><div class="price">'+p.price+'</div><p class="muted">Your configured Stripe/Razorpay provider handles secure recurring billing.</p><button class="primary wide" onclick="startCheckout(\''+plan+'\')">Continue to secure payment →</button>')}
async function startCheckout(plan){try{let r=await api("/payments/checkout",{method:"POST",body:JSON.stringify({plan_code:plan,billing_period:"monthly",currency:"INR"})});if(r.checkout_url)location.href=r.checkout_url;else go("/payment-success")}catch(e){alert(e.message)}}
function pageSuccess(){return generic("Payment Success","Your Spider just got an upgrade.",'<div class="success"><b>✓</b><h2>Welcome to your new plan.</h2><p class="muted">Your subscription will appear after provider confirmation.</p><button class="primary" onclick="go(\'/home\')">Back home</button></div>')}
function route(){let p=location.hash.slice(1)||"/";if(p==="/")return pageSplash();if(p==="/welcome")return pageWelcome();if(p==="/profile-setup")return pageProfileSetup();if(p==="/create-spider")return pageCreateSpider();if(p==="/home")return pageHome();if(p==="/chat")return pageChat();if(p==="/personality")return pagePersonality();if(p==="/pricing")return pagePricing();if(p==="/payment-success")return pageSuccess();if(p.startsWith("/checkout/"))return pageCheckout(p.split("/")[2].toUpperCase());const map={"/history":["Chat history","Your recent conversations."],"/profile":["Profile","Your account and Spider identity."],"/spider":["My Spider","Your companion, your rules."],"/spider/customize":["Spider customization","Name, appearance, and personality."],"/themes":["Themes","Make SpiderGPT yours."],"/saved":["Saved","Your favorite Spider moments."],"/share":["Share Preview","Preview what others see."],"/usage":["Usage Limit","Your plan usage and limits."],"/settings":["Settings","Account, privacy, and app preferences."],"/billing":["Billing & Subscription","Manage your subscription."]};if(map[p])return generic(map[p][0],map[p][1]);return pageSplash()}
async function render(){await syncSession();let p=location.hash.slice(1)||"/";if(p==="/"){document.querySelector("#app").innerHTML=pageSplash();setTimeout(()=>go("/welcome"),900);return}let out=await route();document.querySelector("#app").innerHTML=out}window.addEventListener("hashchange",render);render();